### ISSUE TITLE
question about the confidence score and where is the cosine similarity score

### ISSUE THREAD

**Issue by Huilin-Li** [dzjxzyd/FusionESP#1]
Hi, thanks for your work. I am confused with the output : the confidence socre.

I tested enzyme 2q8m with its substrate fbp (as shown in the figure). I got the confidence score of 0.66. However, the affinity of this pair is already well experimented, shouldn't the affinity of this pair be very close to 1? 
![image](https://github.com/user-attachments/assets/fff435b9-8c6e-4afd-846d-aea196c735c9)

Another question is I can only see the confidence score, may I ask where is the cosine similarity score? 

Thanks in advance!

**Comment by dzjxzyd** [comment]
Thank you for the comments. The confidence score is actually the cosine similarity. Just want to make the results looks like more understandable to user, so we call it confidence score. 
as for the inconsistency between the experimental results and prediction results, it is possible that the model have a poor performance on some datapoints. 
based on our test, if the enzyme or substrates was never seen by the model, the performance was poor. another reason might be the SMILES you used was not canonicalized.
