### ISSUE TITLE
cannot reach https://78k6imn5wp.us-east-1.awsapprunner.com for the cosine similarity socre

### ISSUE THREAD

**Issue by Huilin-Li** [dzjxzyd/FusionESP#2]
Hi, me again.

It is okay to reach https://rqkjkgpsyu.us-east-1.awsapprunner.com/ webserver, but I cannot opoen https://78k6imn5wp.us-east-1.awsapprunner.com server.

Thanks in advance again!

**Comment by dzjxzyd** [comment]
Hi, Thank you for reaching out. The latest server is https://rqkjkgpsyu.us-east-1.awsapprunner.com/

the second one you mentioned has been removed. The latest paper can be arrived at https://www.biorxiv.org/content/10.1101/2024.08.13.607829v2
